//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookids
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Pessoa> Pessoas { get; set; }
        public virtual DbSet<Compra> Compras { get; set; }
        public virtual DbSet<Produto> Produtos { get; set; }
        public virtual DbSet<DetalheCompra> DetalhesCompras { get; set; }
        public virtual DbSet<TipoProduto> TiposProdutos { get; set; }
        public virtual DbSet<Colaboracao> Colaboracoes { get; set; }
        public virtual DbSet<Evento> Eventos { get; set; }
        public virtual DbSet<Participacao> Participacoes { get; set; }
        public virtual DbSet<Escola> Escolas { get; set; }
        public virtual DbSet<Inscricao> Inscricoes { get; set; }
    }
}
